spring:
  application:
    name: fraud-service

  datasource:
    url: jdbc:postgresql://localhost:5432/fraud_db
    username: postgres
    password: 1234567Steven..,
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update  # use 'create' only if you want to reset DB
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8086 # unique port for Fraud Service
